vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        image:
            uri_prefix: /imagesProfil/
            upload_destination: '%kernel.project_dir%/public/imagesProfil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
